### ISSUE TITLE
User can't sell NFT that wasn't created on Zeromint

### ISSUE THREAD

**Issue by treeder** [zeromintapp/community#6] opened 2021-12-31 01:27 UTC
Apparently no sell button shows up after transferring to Zeromint account. 

https://explorer.gochain.io/addr/0xAa8F2Ad1698225F6fdf7E928B7D1CE89E44E3E57?addr_tab=interact

**Comment by wwitkdqsck** [comment] 2021-12-31 15:41
I Tried "ApprovalForAll" Function (Use Contract Tab) ,Transaction when through..but didnt work (i set the  Zeromint Wallet Address)
![explorer-ApprovalForALL](https://user-images.githubusercontent.com/93308499/147830826-69a9b0f0-f54f-46c1-9f76-566ff7c13087.png)

Travis,Can you point in the direction where to start (to fix the problem)..i have no clue actually...thanks

**Comment by wwitkdqsck** [comment] 2022-01-01 06:04
Is the whole Zeromint website a smartcontract on GoChain Network ?Maybe i Should "setApprovalForAll" for the Contract Address...?Just Trying to find Clue..

**Comment by r-gochain** [comment] 2022-01-03 11:27
@wwitkdqsck you should transfer the NFT to the wallet you could find on your profile page

![image](https://user-images.githubusercontent.com/40002763/147925441-78c48af1-cfab-4e94-bcea-b85b26282ab3.png)

**Comment by wwitkdqsck** [comment] 2022-01-03 12:06
Thanks for the input ! Really Appreciate it ! However ive already transfered it to my Zeromint Wallet Address
[Held Tokens](https://explorer.gochain.io/addr/0x35CaBff45283f58CF9B998B186DeB3ccfc62AEaF?addr_tab=owned_tokens) 
![GOB-1](https://user-images.githubusercontent.com/93308499/147928484-e5256292-7f6a-4ccd-9b3b-a9ff61f1db6e.png)
![GOB-2](https://user-images.githubusercontent.com/93308499/147928488-4e01b085-4132-4aa2-b1be-f59271d9f2c9.png)
![GOB-3](https://user-images.githubusercontent.com/93308499/147931205-78334b07-e7fa-45cd-85a6-9a8bf144ba26.png)

**Comment by r-gochain** [comment] 2022-01-03 12:38
@treeder could you check whether the owner has been updated in the database?(owner address and UserID)

**Comment by r-gochain** [comment] 2022-01-03 12:39
@wwitkdqsck what is your wallet public key on the profile page (I see that 0x8AEDEd833466EaD101cBE90a03A28CF067b68B7e is the owner)

**Comment by wwitkdqsck** [comment] 2022-01-03 12:53
Thanks For Helping Guys !
Zeromint Address [0x35CaBff45283f58CF9B998B186DeB3ccfc62AEaF](https://explorer.gochain.io/addr/0x35CaBff45283f58CF9B998B186DeB3ccfc62AEaF?addr_tab=transactions)
![GOB-4](https://user-images.githubusercontent.com/93308499/147932681-71b5f9f9-7676-4078-b9dc-314bef87ea90.png)

**Comment by r-gochain** [comment] 2022-01-03 12:56
@wwitkdqsck what is the token ID that you transferred to this zeromint address?

I checked first 20 and haven't found any transferred

![image](https://user-images.githubusercontent.com/40002763/147933022-0c60f657-97eb-4391-9ac9-063b2b338a40.png)

**Comment by wwitkdqsck** [comment] 2022-01-03 13:00
Try checking token ID 264 to 273 i just minted another 10 to that Zeromint address [GoBears Contract](https://explorer.gochain.io/addr/0xAa8F2Ad1698225F6fdf7E928B7D1CE89E44E3E57?addr_tab=transactions)
![GOB-5](https://user-images.githubusercontent.com/93308499/147933907-b10fe350-48cc-4efb-8b88-3e240fe318ba.png)

**Comment by r-gochain** [comment] 2022-01-03 13:25
confirmed that token 264 has the right owner, @treeder could you check what is the owner_address and userID set in the database for this token (token_id is in the url)

**Comment by wwitkdqsck** [comment] 2022-01-03 13:35
thanks guys !

**Comment by r-gochain** [comment] 2022-01-03 14:10
@wwitkdqsck one more thing - could you confirm the way you import tokens

1. Mint using the contract
2. Transfer to the zeromint wallet
3. Import to the collection
Am I right?

**Comment by wwitkdqsck** [comment] 2022-01-03 14:11
Yes ,thats exactly right sir!

**Comment by r-gochain** [comment] 2022-01-04 11:59
@treeder after merging that PR you also need to reset owner_address (just delete this field in the database for the tokens that have to be reimported) on the imported tokens (it won't reimport it since nothing has changed)

**Comment by wwitkdqsck** [comment] 2022-01-04 13:48
Hello Sir @r-gochain ,just curious after the owner creates a Contract (In this case GoBears - Im the owner ) ,what happen if someone else( a different User ) Imports the contract before me ? will the Collection set to that Users Collections ?And when the Collection is imported for the first time ,can it auto populate all existing NFTs on that contract (so that the collection owner doesnt have to add 1 by 1?

**Comment by r-gochain** [comment] 2022-01-04 13:52
Hey @wwitkdqsck yep that would be his collection, obviously they won't be able to sell anything from this collection
Autopopulation is not really possible because vanilla ERC721 doesn't support token counter as an external variable.

**Comment by wwitkdqsck** [comment] 2022-01-04 13:56
Got it Sir @r-gochain Thanks for the help guys!

**Comment by wwitkdqsck** [comment] 2022-01-05 09:13
Thanks a lot ! @treeder @r-gochain Guys ! Works Perfectly!

Everything Works Now-Buying,Selling,Auction,Transfer Tested it ,,,all works
For the previous Imported NFTs i need to go to the specific NFT page(to sync it ) ..only then it will show up at the User NFTs Section

thanks !
![GOB-6](https://user-images.githubusercontent.com/93308499/148191759-3ab96fc2-8616-4139-a29e-9ced2f2b7fef.png)

**Comment by wwitkdqsck** [comment] 2022-01-05 09:28
Btw,is there a easier way to know all the Token IDs own by a specific Wallet Address ? i can only see there is a Function for BalanceOfHolders or OwnerOf but only returns the total number of NFTs own by an address Or The token ID itself... Pointed out by @r-gochain above ...

**Comment by r-gochain** [comment] 2022-01-05 12:32
@wwitkdqsck vanila contract doesn't support that - https://eips.ethereum.org/EIPS/eip-721

**Comment by r-gochain** [comment] 2022-01-05 12:32
Since everything works I close this issue.

**Closed as completed by r-gochain** 2022-01-05 12:32 UTC

**Comment by wwitkdqsck** [comment] 2022-01-05 13:43
@r-gochain thanks for pointing out https://eips.ethereum.org/EIPS/eip-721 !

**Comment by wwitkdqsck** [comment] 2022-01-05 15:52
Note :
It would be nice if we could store the assets/images/metadata on GoFS.io  in case Pinata.cloud change their Policy for Free Users or Close Down...
I could do it ..but there is no Upload Folder Option in GoFS.io

**Comment by wwitkdqsck** [comment] 2022-01-06 13:44
Guys @r-gochain @treeder actually there is 1 slight problem..apprently only the owner of the collection can Import NFTs?If the Owner of a particular NFT Try  to import it ..gives this error below...
![GOB-ImportError](https://user-images.githubusercontent.com/93308499/148391853-61406283-0440-4e6a-9f5d-9796ca24b3bb.png)

**Comment by r-gochain** [comment] 2022-01-06 14:12
@wwitkdqsck only the owner of the collection can manage the collection

**Comment by wwitkdqsck** [comment] 2022-01-06 14:16
oic ,thanks @r-gochain i can manage 512 Nfts no problem ! Understood...even Opensea is like this...thanks !

**Comment by treeder** [comment] 2022-01-06 14:53
@r-gochain anyone should be able to import an existing NFT in any collection. Even if they don't own the NFT or the collection.

**Comment by r-gochain** [comment] 2022-01-06 14:54
@treeder ok let me fix that

**Comment by r-gochain** [comment] 2022-01-06 15:50
@treeder PR is opened

**Comment by wwitkdqsck** [comment] 2022-01-07 05:28
> Guys @r-gochain @treeder actually there is 1 slight problem..apprently only the owner of the collection can Import NFTs?If the Owner of a particular NFT Try to import it ..gives this error below... ![GOB-ImportError](https://user-images.githubusercontent.com/93308499/148391853-61406283-0440-4e6a-9f5d-9796ca24b3bb.png)

Okay Guys @treeder @r-gochain Different User (Not Collection Owner)  Could Import Now ! Thanks a lot ...already fixed!

**Comment by treeder** [comment] 2022-01-07 12:54
Great!
